### ISSUE TITLE
What are blocked_videos?

### ISSUE THREAD

**Issue by mohammadpz** [activitynet/ActivityNet#2]
Hi all,
Thanks for your nice job! Could you please let me know what are  the blocked_videos?

**Comment by cabaf** [comment]
Hi Mohammad,

Thanks for your interest in our work!

We define "blocked_videos" [here](https://github.com/activitynet/ActivityNet/blob/master/Evaluation/eval_classification.py#L33). The variable contains a list of videos that are either removed or blocked from YouTube. We decided to discard those videos (when performing the evaluation) in order to not penalize people that do not have access to those videos.

**Comment by mohammadpz** [comment]
Oh thanks for your fast reply! However, there are videos there which are not blocked anymore and also there are videos that are now blocked.

**Comment by cabaf** [comment]
Thanks for reporting.

It seems that the daemon that keeps updating the blocked videos died.
I will dig into it and get back to you.

**Comment by cabaf** [comment]
I have updated the daemon in our server. The script is daily checking for blocked/removed videos. If the problem persists, please provide some "videoids" to check what is going on.

Thanks!

**Comment by mohammadpz** [comment]
Thank you!
